services:
  user-service:
    container_name: User-Service
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    depends_on:
      user-service-db:
        condition: service_healthy
#      user-service-redis:
#        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-service-db:5432/user-service-db
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password

  user-service-db:
    image: postgres:17-alpine
    container_name: User-Service-DB
    restart: unless-stopped
    environment:
      POSTGRES_DB: user-service-db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username -d user-service-db" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - user-service-db-data:/var/lib/postgresql/data

#  user-service-redis:
#    image: redis:alpine
#    container_name: User-Service-Redis
#    ports:
#      - "6382:6379"
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      interval: 10s
#      timeout: 5s
#      retries: 10
#    volumes:
#      - user-service-redis-data:/data

volumes:
  user-service-db-data:
#  user-service-redis-data: