server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME}:${EUREKA}/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: user-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5437/user-service-db
    username: username
    password: password

  jpa:
    open-in-view: false
    show-sql: true

    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml


  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all



  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

#jwt:
#  access:
#    secret: 5ba1791dedb87fec844cd4c57bcf5c3afeb0379f4b67347a438bc559b429a52c
#  service:
#    secret: 057f34884f6434c80285a39344a5a47dfd3a571a0ca3e8a65768e76ffc6bb660



#keycloak:
#  server-url: http://localhost:9090
#  realm: test-realm
#  admin:
#    realm: master
#    client-id: admin-cli
#    username: admin
#    password: admin